export const YACHIYO_MAIN_CONTROLS = [
  "ParamAngleX",
  "ParamAngleY",
  "ParamAngleZ",
  "ParamBodyAngleX",
  "ParamBodyAngleY",
  "ParamBodyAngleZ",
  "ParamBreath",
  "ParamCheek",
  "ParamBrowLY",
  "ParamBrowRY",
  "ParamEyeLOpen",
  "ParamEyeROpen",
  "ParamEyeBallX",
  "ParamEyeBallY",
  "ParamMouthForm",
  "ParamMouthOpenY",
  "ParamMouthX",
  "ParamTongueOut",
  "ParamJawOpen",
  "ParamMouthPuckerWiden",
  "ParamCheekPuff",
  "ParamMouthFunnel",
  "ParamMouthPressLipOpen",
  "ParamMouthShrug",
  "ParamExpression_1",
  "ParamExpression_2",
  "ParamExpression_3",
  "ParamExpression_4",
  "ParamHide_EyesL1",
  "ParamHighLightHide_EyesL1",
  "ParamHide_EyeSocket",
  "ParamHide_EyeSocket2",
] as const;

export const YACHIYO_FALLBACK_RANGES: Record<string, [number, number]> = {
  ParamExpression_1: [0, 1],
  ParamExpression_2: [0, 1],
  ParamExpression_3: [0, 1],
  ParamExpression_4: [0, 1],
  ParamHide_EyesL1: [0, 1],
  ParamHighLightHide_EyesL1: [0, 1],
  ParamHide_EyeSocket: [0, 1],
  ParamHide_EyeSocket2: [0, 1],
};

export const COMMON_LIVE2D_CONTROL_RANGES: Record<string, [number, number]> = {
  ParamAngleX: [-30, 30],
  ParamAngleY: [-30, 30],
  ParamAngleZ: [-30, 30],
  ParamBodyAngleX: [-10, 10],
  ParamBodyAngleY: [-10, 10],
  ParamBodyAngleZ: [-10, 10],
  ParamBreath: [0, 1],
  ParamCheek: [0, 1],
  ParamBrowLY: [-1, 1],
  ParamBrowRY: [-1, 1],
  ParamEyeLOpen: [0, 1.5],
  ParamEyeROpen: [0, 1.5],
  ParamEyeSmile_Happy_L: [0, 1],
  ParamEyeSmile_Happy_R: [0, 1],
  ParamEyeSmile_Angry_L: [0, 1],
  ParamEyeSmile_Angry_R: [0, 1],
  ParamEyeLSquint: [0, 1],
  ParamEyeRSquint: [0, 1],
  ParamEyeBallX: [-1, 1],
  ParamEyeBallY: [-1, 1],
  ParamMouthForm: [-1, 1],
  ParamMouthOpenY: [0, 1],
  ParamMouthThickness: [-1, 1],
  ParamMouthStraight: [-1, 1],
  ParamMouthShape: [-1, 1],
  ParamMouthX: [-1, 1],
  ParamTongueOut: [0, 1],
  ParamJawOpen: [0, 1],
  ParamMouthPuckerWiden: [-1, 1],
  ParamCheekPuff: [0, 1],
  ParamCheekPuff2: [0, 1],
  ParamMouthFunnel: [0, 1],
  ParamMouthPressLipOpen: [-1, 1],
  ParamMouthShrug: [0, 1],
  ParamEyeCircles: [0, 1],
  ParamPupilQuake_L1: [0, 1],
  ParamPupilQuake_R1: [0, 1],
  ParamEyeOpenBlink_L1: [0, 1],
  ParamEyeOpenBlink_L2: [0, 1],
  ParamEyeOpenBlinkOF_L1: [0, 1],
  ParamEyeOpenBlinkOF_L2: [0, 1],
  ParamCryDown_L: [0, 1],
  ParamTearDown_1: [0, 1],
  ParamTearDown_2: [0, 1],
  ParamTearDown_3: [0, 1],
  ParamTearDisappear_1: [0, 1],
  ParamTearDisappear_2: [0, 1],
  ParamTearDisappear_3: [0, 1],
  ParamBreathPhysics_L: [0, 1],
  fire: [0, 1],
};

export const YACHIYO_RANGE_OVERRIDES: Record<string, [number, number]> = {
  ParamCheek: [0, 1],
};

export const YACHIYO_UNSAFE_PATTERNS = [
  "Physics",
  "HairPhysics",
  "DressPhysics",
  "SkirtPhysics",
  "SleevePhysics",
  "RibbonPhysics",
  "HighlightPhysics",
];
