export const BASE_EMOTION_PRESETS: Record<string, Record<string, number>> = {
  neutral: {
    ParamAngleX: 0,
    ParamAngleY: 0,
    ParamAngleZ: 0,
    ParamBodyAngleX: 0,
    ParamBodyAngleY: 0,
    ParamBodyAngleZ: 0,
    ParamEyeLOpen: 1,
    ParamEyeROpen: 1,
    ParamEyeBallX: 0,
    ParamEyeBallY: 0,
    ParamBrowLY: 0,
    ParamBrowRY: 0,
    ParamMouthForm: 0,
    ParamMouthOpenY: 0,
    ParamMouthX: 0,
    ParamCheek: 0,
  },
  happy: {
    ParamEyeLOpen: 0.9,
    ParamEyeROpen: 0.9,
    ParamMouthForm: 0.65,
    ParamMouthOpenY: 0.25,
    ParamCheek: 0.35,
    ParamAngleZ: 2,
  },
  shy: {
    ParamAngleY: -3,
    ParamAngleZ: 3,
    ParamEyeLOpen: 0.75,
    ParamEyeROpen: 0.75,
    ParamEyeBallY: -0.25,
    ParamBrowLY: 0.15,
    ParamBrowRY: 0.15,
    ParamMouthForm: 0.45,
    ParamMouthOpenY: 0.06,
    ParamCheek: 0.75,
  },
  embarrassed: {
    ParamAngleY: -4,
    ParamAngleZ: 2.5,
    ParamEyeLOpen: 0.7,
    ParamEyeROpen: 0.7,
    ParamEyeBallY: -0.3,
    ParamBrowLY: 0.25,
    ParamBrowRY: 0.25,
    ParamMouthForm: 0.25,
    ParamMouthOpenY: 0.1,
    ParamCheek: 0.9,
  },
  angry: {
    ParamEyeLOpen: 0.95,
    ParamEyeROpen: 0.95,
    ParamBrowLY: -0.55,
    ParamBrowRY: -0.55,
    ParamMouthForm: -0.45,
    ParamMouthOpenY: 0.05,
    ParamAngleY: 2,
    ParamAngleZ: -2,
  },
  sad: {
    ParamEyeLOpen: 0.65,
    ParamEyeROpen: 0.65,
    ParamEyeBallY: -0.35,
    ParamBrowLY: 0.35,
    ParamBrowRY: 0.35,
    ParamMouthForm: -0.45,
    ParamMouthOpenY: 0.08,
    ParamAngleY: -4,
  },
  crying: {
    ParamExpression_1: 1,
    ParamEyeLOpen: 0.6,
    ParamEyeROpen: 0.6,
    ParamEyeBallY: -0.3,
    ParamBrowLY: 0.45,
    ParamBrowRY: 0.45,
    ParamMouthForm: -0.5,
    ParamMouthOpenY: 0.2,
    ParamCheek: 0.3,
  },
  surprised: {
    ParamEyeLOpen: 1.45,
    ParamEyeROpen: 1.45,
    ParamMouthOpenY: 1.2,
    ParamJawOpen: 0.6,
    ParamMouthForm: -0.1,
    ParamBrowLY: 0.5,
    ParamBrowRY: 0.5,
    ParamAngleY: 2.5,
  },
  confused: {
    ParamEyeLOpen: 0.9,
    ParamEyeROpen: 1.05,
    ParamBrowLY: 0.25,
    ParamBrowRY: -0.2,
    ParamMouthForm: -0.15,
    ParamMouthOpenY: 0.08,
    ParamAngleZ: -2,
  },
  teasing: {
    ParamEyeLOpen: 0.75,
    ParamEyeROpen: 0.9,
    ParamMouthForm: 0.65,
    ParamMouthX: 0.25,
    ParamEyeBallX: -0.25,
    ParamAngleZ: -4,
    ParamCheek: 0.25,
  },
  sleepy: {
    ParamEyeLOpen: 0.35,
    ParamEyeROpen: 0.35,
    ParamEyeBallY: -0.2,
    ParamBrowLY: 0.15,
    ParamBrowRY: 0.15,
    ParamMouthForm: 0.05,
    ParamMouthOpenY: 0.03,
    ParamAngleY: -3,
  },
  panic: {
    ParamEyeLOpen: 1.35,
    ParamEyeROpen: 1.35,
    ParamEyeBallY: 0.2,
    ParamBrowLY: 0.65,
    ParamBrowRY: 0.65,
    ParamMouthForm: -0.25,
    ParamMouthOpenY: 0.9,
    ParamJawOpen: 0.4,
    ParamAngleZ: 3,
  },
};

